url: "https://www.newsushi.city" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "New Sushi City" # the name of your site, e.g. ACME Corp.
